components:
  schemas: {}
info:
  contact:
    name: Koji Endo
  description: two-photon api
  title: 2pAPI
  version: '1.0'
openapi: 3.0.0
tags:
  - name: stage-scan
servers:
  - url: 192.168.2.100
  - url: 192.168.2.104
paths:
  /prudaq:
    post:
      description: control prudaq udp sending
      operationId: prudaq
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  address: 192.168.2.100
                  bufferSize: 64020
                  count: 73849954
                  udpPort: 60000
                  uuid: yo20210222-125814
            schema:
              properties:
                address:
                  type: string
                bufferSize:
                  type: integer
                count:
                  type: integer
                udpPort:
                  type: integer
                uuid:
                  type: string
              required:
                - count
              type: object
        description: ''
      responses:
        '200':
          description: OK
      summary: /prudaq
      tags:
        - stage-scan
  /prudaq/kill-lite:
    post:
      description: prudaq kill usend process
      operationId: prudaq-killlite
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value: {}
            schema:
              type: object
      responses:
        '200':
          description: OK
      summary: /prudaq/kill-lite
      tags:
        - stage-scan
  /receiver:
    post:
      description: control ./receiver_main
      operationId: receiver
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  daServer:
                    enabled: false
                    host: 0.0.0.0
                    path: /da/mock
                    port: 9090
                  description: gain50
                  fileSave:
                    debug: octo_test/0220/
                    enabled: true
                    rawData: octo_test/0220/
                    rawDataSave: false
                    tiffSave: true
                  galvo: false
                  image:
                    dataChan: 0
                    pixelDataNum: 5
                    sizeX: 1024
                    sizeY: 1024
                    sizeZ: 5
                    threshold: 100
                    xFSteps: 4096
                    yFStepSeqs: 100
                  scanData:
                    aomOpenHl: 1
                    aomOpenUs: 50
                    command: scan
                    delay: 0.5
                    description: gain50
                    invert: 0
                    lengthX: 1024
                    lengthY: 1024
                    pinConfig:
                      - name: plsPin1
                        value: 1
                      - name: dirPin1
                        value: 2
                      - name: plsPin2
                        value: 3
                      - name: dirPin2
                        value: 4
                      - name: plsPin3
                        value: 5
                      - name: dirPin3
                        value: 6
                      - name: aomPin
                        value: 7
                      - name: aomRef
                        value: 8
                    stepPeriodX: 75
                    stepPeriodY: 500
                    stepPeriodZ: 500
                    uuid: bp20210222-125315
                    xBSteps: 4096
                    xFSteps: 4096
                    xyRepeatNum: 300
                    xyzRepeatNum: 1
                    yBSteps: 1024
                    yFStepSeqs: 1024
                    yFStepsPerSeq: 1
                    zBSteps: 1
                    zFStepsPerSeq: 1
                    zFStepSeqs: 1
                  udp:
                    bufferNum: 4096
                    bufferSize: 64020
                    count: 73849954
                    enabled: true
                    host: 192.168.2.100
                    port: 60000
                  uuid: bp20210222-125315
                  verbosity: false
                  websocket:
                    host: 0.0.0.0
                    enabled: true
                    interval: 100
                    port: 8072
            schema:
              properties:
                daServer:
                  properties:
                    enabled:
                      type: boolean
                    host:
                      type: string
                    path:
                      type: string
                    port:
                      type: integer
                  required:
                    - enabled
                    - host
                    - path
                    - port
                  type: object
                description:
                  type: string
                fileSave:
                  properties:
                    debug:
                      type: string
                    enabled:
                      type: boolean
                    rawData:
                      type: string
                    rawDataSave:
                      type: boolean
                    tiffSave:
                      type: boolean
                  required:
                    - debug
                    - enabled
                    - rawData
                    - rawDataSave
                    - tiffSave
                  type: object
                galvo:
                  type: boolean
                image:
                  properties:
                    dataChan:
                      type: integer
                    pixelDataNum:
                      type: integer
                    sizeX:
                      type: integer
                    sizeY:
                      type: integer
                    sizeZ:
                      type: integer
                    threshold:
                      type: integer
                    xFSteps:
                      type: integer
                    yFStepSeqs:
                      type: integer
                  required:
                    - dataChan
                    - pixelDataNum
                    - sizeX
                    - sizeY
                    - sizeZ
                    - threshold
                    - xFSteps
                  type: object
                scanData:
                  properties:
                    aomOpenHl:
                      type: integer
                    aomOpenUs:
                      type: integer
                    command:
                      type: string
                    delay:
                      type: number
                    description:
                      type: string
                    invert:
                      type: integer
                    lengthX:
                      type: integer
                    lengthY:
                      type: integer
                    pinConfig:
                      items:
                        properties:
                          name:
                            type: string
                          value:
                            type: integer
                        required:
                          - name
                          - value
                        type: object
                      type: array
                    stepPeriodX:
                      type: integer
                    stepPeriodY:
                      type: integer
                    stepPeriodZ:
                      type: integer
                    uuid:
                      type: string
                    xBSteps:
                      type: integer
                    xFSteps:
                      type: integer
                    xyRepeatNum:
                      type: integer
                    xyzRepeatNum:
                      type: integer
                    yBSteps:
                      type: integer
                    yFStepSeqs:
                      type: integer
                    yFStepsPerSeq:
                      type: integer
                    zBSteps:
                      type: integer
                    zFStepsPerSeq:
                      type: integer
                    zFStepSeqs:
                      type: integer
                  required:
                    - aomOpenHl
                    - aomOpenUs
                    - command
                    - delay
                    - description
                    - invert
                    - lengthX
                    - lengthY
                    - pinConfig
                    - stepPeriodX
                    - stepPeriodY
                    - stepPeriodZ
                    - uuid
                    - xBSteps
                    - xFSteps
                    - xyRepeatNum
                    - xyzRepeatNum
                    - yBSteps
                    - yFStepSeqs
                    - yFStepsPerSeq
                    - zBSteps
                    - zFStepsPerSeq
                    - zFStepSeqs
                  type: object
                udp:
                  properties:
                    bufferNum:
                      type: integer
                    bufferSize:
                      type: integer
                    count:
                      type: integer
                    enabled:
                      type: boolean
                    host:
                      type: string
                    port:
                      type: integer
                  required:
                    - bufferNum
                    - bufferSize
                    - count
                    - enabled
                    - host
                    - port
                  type: object
                uuid:
                  type: string
                verbosity:
                  type: boolean
                websocket:
                  properties:
                    enabled:
                      type: boolean
                    host:
                      type: string
                    interval:
                      type: integer
                    port:
                      type: integer
                  required:
                    - enabled
                    - host
                    - interval
                    - port
                  type: object
              required:
                - daServer
                - fileSave
                - image
                - udp
                - websocket
                - galvo
                - uuid
                - verbosity
              type: object
      responses:
        '200':
          description: OK
      summary: /receiver
      tags:
        - stage-scan
  /receiver/ps:
    post:
      description: get ps of ./receiver_main.out
      operationId: receiver-ps
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value: {}
            schema:
              type: object
      responses:
        '200':
          description: OK
      summary: /receiver/ps
      tags:
        - stage-scan
  /receiver/signal:
    post:
      description: send signal to ./receiver_main.out
      operationId: receiver-signal
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  signum: 2
            schema:
              properties:
                signum:
                  type: integer
              required:
                - signum
              type: object
      responses:
        '200':
          description: OK
      summary: /receiver/signal
      tags:
        - stage-scan
  /stage/aom:
    post:
      description: toggle aom on and off
      operationId: stage-aom
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  aomOnoff: 1
                  aomOpenHl: 1
                  invert: 0
                  pinConfig:
                    - name: plsPin1
                      value: 1
                    - name: dirPin1
                      value: 2
                    - name: plsPin2
                      value: 3
                    - name: dirPin2
                      value: 4
                    - name: plsPin3
                      value: 5
                    - name: dirPin3
                      value: 6
                    - name: aomPin
                      value: 7
                    - name: aomRef
                      value: 8
                  stepPeriodX: 75
                  stepPeriodY: 500
                  stepPeriodZ: 500
                  uuid: yb20210222-130053
            schema:
              properties:
                pinConfig:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: integer
                    required:
                      - name
                      - value
                command:
                  type: string
                  description: '0'
                invert:
                  type: integer
                  description: '1'
                stepPeriodX:
                  type: integer
                  description: '2'
                stepPeriodY:
                  type: integer
                  description: '3'
                stepPeriodZ:
                  type: integer
                  description: '4'
                aomOpenHl:
                  type: integer
                  description: '5'
                aomOnoff:
                  type: integer
                  description: '6'
                uuid:
                  type: string
              required:
                - command
                - aomOnoff
                - aomOpenHl
                - invert
                - pinConfig
                - stepPeriodX
                - stepPeriodY
                - stepPeriodZ
              type: object
      responses:
        '200':
          description: OK
      summary: /stage/aom
      tags:
        - stage-scan
  /stage/move:
    post:
      description: control stage move
      operationId: stage-move
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  aomOpenHl: 1
                  command: move
                  direction: 0
                  invert: 0
                  moveLength: 0
                  pinConfig:
                    - name: plsPin1
                      value: 1
                    - name: dirPin1
                      value: 2
                    - name: plsPin2
                      value: 3
                    - name: dirPin2
                      value: 4
                    - name: plsPin3
                      value: 5
                    - name: dirPin3
                      value: 6
                    - name: aomPin
                      value: 7
                    - name: aomRef
                      value: 8
                  stepPeriodX: 75
                  stepPeriodY: 500
                  stepPeriodZ: 500
                  steps: 0
                  uuid: cf20210222-125331
            schema:
              properties:
                pinConfig:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: integer
                    required:
                      - name
                      - value
                    type: object
                  type: array
                command:
                  type: string
                  description: '0'
                invert:
                  type: integer
                  description: '1'
                stepPeriodX:
                  type: integer
                  description: '2'
                stepPeriodY:
                  type: integer
                  description: '3'
                stepPeriodZ:
                  type: integer
                  description: '4'
                aomOpenHl:
                  type: integer
                  description: '5'
                direction:
                  type: integer
                  description: '6'
                steps:
                  type: integer
                  description: '7'
                moveLength:
                  type: integer
                uuid:
                  type: string
              required:
                - aomOpenHl
                - command
                - direction
                - invert
                - pinConfig
                - stepPeriodX
                - stepPeriodY
                - stepPeriodZ
                - steps
              type: object
      responses:
        '200':
          description: OK
      summary: /stage/move
      tags:
        - stage-scan
  /stage/scan:
    post:
      description: control stage scan
      operationId: stage-scan
      requestBody:
        description: 'pinConfig:16 bit * 12, 0-: 32 bit'
        content:
          application/json:
            examples:
              example-1:
                value:
                  aomOpenHl: 1
                  aomOpenUs: 50
                  command: scan
                  delay: 0
                  description: gain50
                  invert: 0
                  lengthX: 1024
                  lengthY: 1024
                  pinConfig:
                    - name: plsPin1
                      value: 1
                    - name: dirPin1
                      value: 2
                    - name: plsPin2
                      value: 3
                    - name: dirPin2
                      value: 4
                    - name: plsPin3
                      value: 5
                    - name: dirPin3
                      value: 6
                    - name: aomPin
                      value: 7
                    - name: aomRef
                      value: 8
                  stepPeriodX: 75
                  stepPeriodY: 500
                  stepPeriodZ: 500
                  uuid: kd20210222-130129
                  xBSteps: 4096
                  xFSteps: 4096
                  xyRepeatNum: 300
                  xyzRepeatNum: 1
                  yBSteps: 1024
                  yFStepSeqs: 1024
                  yFStepsPerSeq: 1
                  zBSteps: 1
                  zFStepsPerSeq: 1
                  zFStepSeqs: 1
            schema:
              type: object
              properties:
                pinConfig:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: integer
                    required:
                      - name
                      - value
                command:
                  type: string
                  description: '00'
                invert:
                  type: integer
                  description: '01'
                stepPeriodX:
                  type: integer
                  description: '02'
                stepPeriodY:
                  type: integer
                  description: '03'
                stepPeriodZ:
                  type: integer
                  description: '04'
                aomOpenHl:
                  type: integer
                  description: '05'
                aomOpenUs:
                  type: integer
                  description: '06'
                xFSteps:
                  type: integer
                  description: '07'
                xBSteps:
                  type: integer
                  description: '08'
                yFStepSeqs:
                  type: integer
                  description: '09'
                yFStepsPerSeq:
                  type: integer
                  description: '10'
                yBSteps:
                  type: integer
                  description: '11'
                zFStepSeqs:
                  type: integer
                  description: '12'
                zFStepsPerSeq:
                  type: integer
                  description: '13'
                zBSteps:
                  type: integer
                  description: '14'
                xyRepeatNum:
                  type: integer
                  description: '15'
                xyzRepeatNum:
                  type: integer
                  description: '16'
                delay:
                  type: integer
                description:
                  type: string
                lengthX:
                  type: integer
                lengthY:
                  type: integer
                uuid:
                  type: string
              required:
                - aomOpenHl
                - aomOpenUs
                - command
                - invert
                - pinConfig
                - stepPeriodX
                - stepPeriodY
                - stepPeriodZ
                - xBSteps
                - xFSteps
                - xyRepeatNum
                - xyzRepeatNum
                - yBSteps
                - yFStepSeqs
                - yFStepsPerSeq
                - zBSteps
                - zFStepsPerSeq
                - zFStepSeqs
      responses:
        '200':
          description: OK
      summary: /stage/scan
      tags:
        - stage-scan
  /stage/stop:
    post:
      summary: stage-stop
      description: stop the stage scan
      operationId: stage-stop
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  aomOpenHl: 1
                  command: stop
                  goBack: 1
                  invert: 0
                  pinConfig:
                    - name: plsPin1
                      value: 1
                    - name: dirPin1
                      value: 2
                    - name: plsPin2
                      value: 3
                    - name: dirPin2
                      value: 4
                    - name: plsPin3
                      value: 5
                    - name: dirPin3
                      value: 6
                    - name: aomPin
                      value: 7
                    - name: aomRef
                      value: 8
                  stepPeriodX: 75
                  stepPeriodY: 500
                  stepPeriodZ: 500
                  uuid: ow20210222-131248
            schema:
              properties:
                pinConfig:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: integer
                    required:
                      - name
                      - value
                command:
                  type: string
                  description: '00'
                invert:
                  type: integer
                  description: '01'
                stepPeriodX:
                  type: integer
                  description: '02'
                stepPeriodY:
                  type: integer
                  description: '03'
                stepPeriodZ:
                  type: integer
                  description: '04'
                aomOpenHl:
                  type: integer
                  description: '05'
                goBack:
                  type: integer
                  description: '06'
                uuid:
                  type: string
              required:
                - aomOpenHl
                - command
                - goBack
                - invert
                - pinConfig
                - stepPeriodX
                - stepPeriodY
                - stepPeriodZ
              type: object
      responses:
        '200':
          description: OK
      tags:
        - stage-scan
  /tiff/list:
    get:
      description: listup tiff in the designated folder.
      operationId: tiff-list
      responses:
        '200':
          description: OK
      summary: /tiff/list
      tags:
        - stage-scan
      parameters:
        - schema:
            type: string
            example: "0320"
          in: query
          name: folder
          required: true
          description: ''
  /tiff/file:
    get:
      description: get tiff file
      operationId: tiff-file
      parameters:
        - schema:
            type: string
            example: "0320"
          in: query
          name: folder
          required: true
          description: ''
        - schema:
            type: string
            example: "aw20210323-225248.tiff"
          in: query
          name: filename
          required: true
          description: ''
        - schema:
            type: string
            example: "tiff,json"
          in: query
          name: filetype
          required: true
          description: ''
        - schema:
            type: boolean
          in: query
          name: renew
          required: false
          description: ''
      responses:
        '200':
          description: OK
      summary: /tiff/file
      tags:
        - stage-scan
